### PR TITLE
Add deserializeUnsafe and serializeExn

### LINKED ISSUE #208: Add Js.Json.deserializeUnsafe and Js.Json.serializeExn to the docs
It looks like `Js.Json.deserializeUnsafe` and `Js.Json.serializeExn` are not currently in the docs.

https://rescript-lang.org/docs/manual/latest/api/js/json

Should they be added? Or perhaps intentionally omitted?

### PR DESCRIPTION
**Pull request by kevanstannard**
Fixes #208

As discussed, suggestion content for these functions.

### CODE REVIEW

**Comment by ryyppy** [comment]
Sorry for my slow responsiveness. The problem is that these functions are not serializing / deserializing JSON data to string and vice versa. They are serializing / deserializing records (that e.g. contain `option` value attributes) into a JSON compliant JSON object... really hard to explain, because as I said, I am not fully aware of the edge-cases and implications on more complex records.

I actually wrote a whole post about the original problem this api tried to solve [here](https://dev.to/ryyppy/reason-records-nextjs-undefined-and-getstaticprops-5d46).

Try it on a node script and see what `Js.log` prints.

**Comment by ryyppy** [comment]
So the correct description should go along the line of: those functions are useful to quickly serialize / deserialize a record into a JSON compliant string... probably also works for other ReScript internal data structures, but not sure.

**Comment by kevanstannard** [comment]
@ryyppy thanks for the feedback - copy updated.

Can you please confirm this is correct for `deserializeUnsafe`:

> Deserializes a JSON string created by `serializeExn()` into a ReScript record.

Feel free to suggest improvements.

**Comment by kevanstannard** [comment]
Hi @ryyppy just following up on this one.

I was thinking about this one some more. Do you feel these functions are still worth documenting? Would you consider them experimental?

Happy to be guided by you.

**Comment by kevanstannard** [comment]
👍 sounds good. Closing.

**Pull request closed without merging**
