### PR TITLE
Document warning numbers

### LINKED ISSUE #190: Add available warning numbers for @@warning()
We already map our warnings numbers in our playground (check the "Settings" tab, and try to add a warning to see the number recommendations).

The same data could be used to list all the available warnings in our Attribute / Decorator docs. Might be a little tricky to list them all, so might be worth making the list interactive.

### PR DESCRIPTION
**Pull request by Minnozz**
Fixes #190

### CODE REVIEW

**Comment by ryyppy** [comment]
This looks generally pretty good.

A few things:
- Not sure if we should call the sidebar navigation item `Compiler Warnings`... sounds more like an FAQ collection of error messages (problem -> solution). Maybe `Warning Numbers` would be better?
- I noticed that our Warnings collection has deviated from upstream (still a bunch of BuckleScript words in there). Here's the most up to date list: [warnings.ml](https://github.com/rescript-lang/ocaml/blob/2930b685e73fd60a63181a939ba641f63b50c588/utils/warnings.ml#L667-L753)

Probably unrelated to this list, but I also wanted to have a simple text field to fuzzy find particular warning numbers by description. In a similar manner how we did it with the Syntax Lookup Widget (using the Fuse.res bindings), but this can be done in another task.

**Comment by ryyppy** [comment]
Nice! One last thing: 

Can we change the link within [this section](https://rescript-langorg-mk5t2ikrt-rescript-association.vercel.app/docs/manual/latest/build-configuration#warnings) to point to the new warning-number list?

That will be the last change, otherwise it looks perfect!

**Comment by Minnozz** [comment]
We might want to link to the new warning list (or embed `<WarningTable />`) on some more pages: https://github.com/rescript-association/rescript-lang.org/issues/190#issuecomment-860908936

**Comment by ryyppy** [comment]
> We might want to link to the new warning list 

Yeah, in the attribute page we could add a link to the warning list in the description here:
image

`You can find a full list of all available warnings [here](...)`

> most useful would be the syntax widget I think

I'd not include the whole table into different pages... should be enough to link to it, no? In the Syntax widget we use the `See` section to link to canonical resources

**Comment by Minnozz** [comment]
I've added some more links to and from the Warning Numbers page, and I also added the `@@warning` decorator to the syntax widget. I'm not entirely sure if I'm correct that it operates on the module level; somewhere else it is stated that it operates on the file.

**Comment by ryyppy** [comment]
this is looking sleek. Thanks!

**Pull request merged**
