### PR TITLE
document hyphens in tag names

### PR DESCRIPTION
**Pull request by tsnobip**
Document a feature brought by rescript-lang/rescript-compiler#6609

### CODE REVIEW

**Review by zth — APPROVED** [review]

**Comment by fhammerschmidt** [comment]
Can we merge this now?

**Comment by tsnobip** [comment]
> Can we merge this now?

I think so

**Comment by zth** [comment]
We just need to up the ReScript version so tests pass.

**Comment by zth** [comment]
@tsnobip I updated the version in a recently merged PR so you can just rebase.

**Comment by tsnobip** [comment]
> @tsnobip I updated the version in a recently merged PR so you can just rebase.

done!

**Pull request merged**
