### PR TITLE
use css marker pseudo-element

### PR DESCRIPTION
**Pull request by aspeddro**
This change increase the space between bullet/dash and start of `p`

Close: #474

### CODE REVIEW

**Comment by ryyppy** [comment]
Hm, doesn't seem to work on iOS Safari (iPhone 13 Pro):

IMG_544071F61532-1

**Comment by ryyppy** [comment]
the latest coming with iOS 15.4.1

**Comment by ryyppy** [comment]
Looking good! Ready for merge?

**Comment by aspeddro** [comment]
yes

**Comment by ryyppy** [comment]
thanks!

**Pull request merged**
