### PR TITLE
Add Tiny logo to users of ReScript

### PR DESCRIPTION
**Pull request by TheSpyder**
TinyMCE uses ReScript for our [real-time collaboration offering](https://www.tiny.cloud/tinymce/features/real-time-collaboration/).

It's closed source, but our long term plan (1-2 years) is to [open source the new editor model](https://www.tiny.cloud/blog/real-time-collaborative-editing-slate-js/) which is a big chunk of the feature.

Side note:
The Tiny logo looks a tad out of place as our branding doesn't have whitespace around the edges. I'm not an SVG expert so I'm not sure how to add that; maybe the logos need a way to add CSS padding for situations like this.

### CODE REVIEW

**Comment by vmarcosp** [comment]
I can help you with the whitespace, can I send a version of your logo with the same space that I used in my PR?

**Comment by TheSpyder** [comment]
Is that the `clipPath`? Yeah that would be great thanks :)

**Comment by vmarcosp** [comment]
> Is that the clipPath? Yeah that would be great thanks :)

I'm not sure, but I edited the SVG with figma. Take a look:


_Before (original)_
image

_After (edited with whitespaces)_
image

The svg:
```svg
<svg width="126" height="48" viewBox="0 0 126 48" fill="none" xmlns="http://www.w3.org/2000/svg">
<g clip-path="url(#clip0_1107_875)">
<path fill-rule="evenodd" clip-rule="evenodd" d="M101.501 14.6562L104.945 24.3536L105.765 27.3121L106.748 24.3536L110.192 14.6562H115.603L106.568 39.9024L100.731 41.0529L103.141 34.2154L96.0904 14.6562H101.501ZM32.3348 6.7832C37.9087 6.81606 43.4171 11.4491 43.4171 18.2015C43.4171 18.2015 43.4533 20.0052 43.4559 22.1525L43.456 22.5676C43.4556 23.0325 43.4535 23.5088 43.4489 23.9823L43.4459 24.266C43.425 26.0593 43.3675 27.7725 43.2367 28.634C42.4662 33.7928 38.6137 37.3579 33.302 38.2615C28.515 39.198 25.6789 39.7402 24.7608 39.9209C24.5294 39.9692 23.8328 40.0687 23.1449 40.1424L23.0075 40.1568C22.5739 40.2011 22.1565 40.233 21.8755 40.233C16.0393 40.233 10.7441 35.8629 10.6621 28.8148L10.6623 28.462C10.6623 28.4446 10.6623 28.4267 10.6623 28.4081L10.6624 28.2265C10.6632 27.376 10.6656 25.7187 10.6736 24.0294L10.6756 23.6393L10.677 23.3797C10.6865 21.695 10.7021 20.0775 10.7277 19.3022C10.9244 14.1599 14.4819 10.0033 21.2525 8.67256L21.2624 8.67065C21.5805 8.60878 29.5383 7.06119 29.8757 6.99678C30.6626 6.84892 31.5315 6.7832 32.3348 6.7832ZM59.5251 9.39658V14.6562H64.4442V19.4227H59.5251V27.6409C59.5251 29.2516 60.7385 29.942 61.4927 29.942C62.2073 29.942 62.8483 29.8534 63.5133 29.6485L63.6243 29.6132L64.7721 33.3936C64.2802 33.7223 62.8045 34.5441 60.017 34.5441C57.2295 34.5441 54.3437 32.4074 54.2781 28.7914C54.2548 27.6469 54.2425 26.3439 54.2413 24.8822V24.3891C54.2425 22.9603 54.2537 21.3869 54.275 19.6691L54.2781 19.4227H50.8347V14.6562H54.2781V10.4156L59.5251 9.39658ZM36.2365 12.7799L23.1214 15.3264V20.4523L17.8754 21.4709V34.2528L30.9905 31.7063V26.5804L36.2365 25.5618V12.7799ZM87.4 14.1631C92.0101 14.1306 95.4954 17.8031 95.5964 22.4059L95.5985 22.5456V34.2154H90.3514V23.3674C90.335 20.902 88.5478 18.9132 86.0882 18.9296C83.6533 18.9459 81.5237 20.8631 81.4972 23.2936L81.4971 34.2154H76.25V14.6562H81.0051L81.1855 16.9408C82.7104 15.2643 84.9568 14.1795 87.4 14.1631ZM72.9706 14.6562V34.2154H67.7236V14.6562H72.9706ZM30.9905 18.9244V26.5804L23.1214 28.1083V20.4523L30.9905 18.9244ZM72.9706 6.7832V11.8949L67.7236 12.9139V7.80225L72.9706 6.7832Z" fill="#979AAD"/>
</g>
<defs>
<clipPath id="clip0_1107_875">
<rect width="104.613" height="33.7778" fill="white" transform="translate(10.666 7.11108)"/>
</clipPath>
</defs>
</svg>
```

**Comment by TheSpyder** [comment]
Ah it's changed quite a bit. I guess the clip path is related but not the whole story. Oh well. Thanks for your help :)

**Comment by ryyppy** [comment]
Done. Thanks!

**Pull request merged**
