### PR TITLE
feat: add prev and next button

### LINKED ISSUE #601: Feature Request: Prev and Next Buttons
It is really cumbersome to navigate docs in sequential manner. Please can you add PREV and NEXT buttons to the website (both on the top and the bottom of the page if possible). Strong connection and easy navigation improves spatial memory, bolster learning and recollection, especially on re-visits. I am sure it will help with the adoption rate.

Something like the ones on this page: https://www.typescriptlang.org/docs/handbook/2/basic-types.html. And maybe with simple or less intrusive top buttons which is missing on the above link.

Thank you.

### PR DESCRIPTION
**Pull request by aspeddro**
Close #601

### CODE REVIEW

**Comment by ryyppy** [comment]
Can you please rebase onto latest master to get a successful build?

**Comment by aspeddro** [comment]
> Can you please rebase onto latest master to get a successful build?

Done

**Comment by ryyppy** [comment]
Looking great so far!

Could add a border with a slightly lighter color than the text and some border radius? Would make it more obvious that this is clickable.

**Comment by ryyppy** [comment]
Thanks!

**Pull request merged**
