### PR TITLE
Syntax lookup: Warning decorator

### PR DESCRIPTION
**Pull request by kevanstannard**
Suggestion for #162 

**PR should be editable, please feel free edit.**

### CODE REVIEW

**Comment by kevanstannard** [comment]
@ryyppy yes, the different syntaxes seem to be working. I tried the following:

```res
@warning("-32")
let x = 0 // No warning here
let x = 1

let y = 0 // "unused value y" warning here
let y = 1
```

As with your comment on the  `@deprecated` PR, what do you think about making these separate pages for Syntax Lookup?

Anything else to consider?

**Comment by ryyppy** [comment]
Two separate pages are fine. Just let's make it clear that the decorator applies to an expression / module.

**Comment by kevanstannard** [comment]
@ryyppy PR updated, see what you think.

Also, could I double check something? In the PR I wrote that the decorators are use to _enable or disable_ warnings. Is it correct that they can _enable_ warnings, or are they exclusively used for disabling warnings?

**Comment by ryyppy** [comment]
> Is it correct that they can enable warnings, or are they exclusively used for disabling warnings?
You can do both: Enable (`@warning("+27")`) or Disable (`@warning("-27")`)

**Comment by kevanstannard** [comment]
Thanks @ryyppy 

I've made some tweaks, see what you think.

**Comment by bobzhang** [comment]
My concern with issue is that this is a buggy feature which has its use case but very hard to implement it correctly.

**Comment by kevanstannard** [comment]
Syntax Lookup @@warning is documented now, so let's close this one off.

**Pull request closed without merging**
