### PR TITLE
fix: use uncurrying to generate method calls after 9.1

### PR DESCRIPTION
**Pull request by glennsl**
Quick fix to generate the same JS code after 9.1. Addresses #611.

Credit goes to @DZakh for the suggestion.

### CODE REVIEW

**Comment by cristianoc** [comment]
Thanks for the fix.
Not sure why vercel has become unhappy. Seems unrelated, but without vercel there's no deployment.
Maybe @ryyppy has some idea.

**Comment by cristianoc** [comment]
```
Error: error:0308010C:digital envelope routines::unsupported
--
11:19:38.670 | at new Hash (node:internal/crypto/hash:71:19)
11:19:38.670 | at Object.createHash (node:crypto:133:10)
11:19:38.670 | at BulkUpdateDecorator.hashFactory (/vercel/path0/node_modules/next/dist/compiled/webpack/bundle5.js:133790:18)
11:19:38.670 | at BulkUpdateDecorator.update (/vercel/path0/node_modules/next/dist/compiled/webpack/bundle5.js:133692:50)
11:19:38.670 | at /vercel/path0/node_modules/next/dist/compiled/webpack/bundle5.js:56905:9
11:19:38.670 | at processTicksAndRejections (node:internal/process/task_queues:82:21)
11:19:38.671 | at runNextTicks (node:internal/process/task_queues:64:3)
11:19:38.671 | at process.processImmediate (node:internal/timers:442:9) {
11:19:38.671 | opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
11:19:38.671 | library: 'digital envelope routines',
11:19:38.671 | reason: 'unsupported',
11:19:38.671 | code: 'ERR_OSSL_EVP_UNSUPPORTED'
11:19:38.671 | }
11:19:38.671 |  
11:19:38.671 | Node.js v18.12.1
11:19:38.702 | Error: Command "npm run build" exited with 1
````

**Comment by DZakh** [comment]
Try to redeploy it without an existing cache. It quite often helps with this kind of problem.

**Comment by ryyppy** [comment]
Can you rebase onto latest master?

**Comment by glennsl** [comment]
Tried a new "sync" button that apparently does a merge instead of rebase, but... Done!

**Review by cristianoc — APPROVED** [review]

**Comment by ryyppy** [comment]
Thanks!

**Pull request merged**
