### PR TITLE
Add new templates urls

### PR DESCRIPTION
**Pull request by aspeddro**
~~Remove templates section from Landing page.~~

Add new template URLs to repo https://github.com/rescript-lang/create-rescript-app

image

### CODE REVIEW

**Comment by ryyppy** [comment]
I'd still want to highlight on the landing page what's available within create-rescript-app. How does one know what ReScript supports out of the box?

**Comment by aspeddro** [comment]
@fhammerschmidt `create-rescript-app` support arguments? We can add code block like `create-rescript-app --with-nextjs`

**Comment by ryyppy** [comment]
I think this card should just link to the getting started page with the relevant create-rescript-app snippet... ideally later on to an actual nextjs tutorial page that uses that npx command.

I would probably not put that install link right on the card or on the front page

**Comment by aspeddro** [comment]
This can be merged when `create-rescript-app` 1.6.0 is released.


cc @cknitt @fhammerschmidt

**Comment by fhammerschmidt** [comment]
Will merge this now, as the release is today.

**Pull request merged**
