### PR TITLE
Render React in playground

### PR DESCRIPTION
**Pull request by tsnobip**
Now ready for review @fhammerschmidt :)

### CODE REVIEW

**Comment by fhammerschmidt** [comment]
Do you think the react deps should be listed here as well?
image

**Comment by tsnobip** [comment]
> Do you think the react deps should be listed here as well? image

I don't think so, those are ReScript dependencies.

**Comment by tsnobip** [comment]
I'm actually wondering if a Console panel is that much needed, one could just open the console of the browser and have a better rendering of the logs, what do you guys think?

**Comment by fhammerschmidt** [comment]
I would keep the Console tab but maybe we can have a hybrid of both Rendering and Console. In practice you most often want to have either Console or HTML, only more convoluted examples may have both.

**Comment by tsnobip** [comment]
That's an interesting idea, we could do that in a follow-up PR. We could use "output" as the name of this tab.

**Comment by fhammerschmidt** [comment]
Why would we want to add a new tab now only to remove it again later? Let's just add it here. Or hide it and only reveal it in the next PR.

**Comment by tsnobip** [comment]
@fhammerschmidt can you take a look, in the last commit I shipped the "Output" layout, there's the react panel first then the console output. Let me know if you prefer this.

To be honest, I still think we should rather use the built-in browser dev console for the console output.

**Comment by fhammerschmidt** [comment]
this got merged in #875 🎉

**Pull request closed without merging**
