### PR TITLE
Invalid props for Non DOM Components

### PR DESCRIPTION
**Pull request by srikanthkyatham**
Updating documentation for passing `aria-*` props to Non DOM components

### CODE REVIEW

**Comment by ryyppy** [comment]
Hm, I read this sentence it was more confusing to me than before.

We are separating between DOM elements `<div/>` and actual React components `<MyButton/>`. You want to make clear that for React component props, the `aria-` transformation doesn't apply, right?

I still don't understand the motivation for this, because if you are creating a component that does introduce a `~ariaLabel` prop, it would still need to apply that argument to a DOM element somewhere.

```res
@react.component
  let make = (~ariaLabel: string) => {
    <button ariaLabel> {"test"->React.string} </button>
  }
```

I don't see any scenario where this might be an issue?

**Comment by srikanthkyatham** [comment]
Hi @ryyppy 


> Hm, I read this sentence it was more confusing to me than before.
> 
> We are separating between DOM elements `<div/>` and actual React components `<MyButton/>`. You want to make clear that for React component props, the `aria-` transformation doesn't apply, right?
> 

Yes your understanding is correct 

> I still don't understand the motivation for this, because if you are creating a component that does introduce a `~ariaLabel` prop, it would still need to apply that argument to a DOM element somewhere.
> 
> ```rescript
> @react.component
>   let make = (~ariaLabel: string) => {
>     <button ariaLabel> {"test"->React.string} </button>
>   }
> ```
> 
> The `<button>` element is doing the transform correctly, so can't see any scenario where this might be an issue?

The use case was pass aria-* props to React components from a ui library. In our case a company's ui library.

**Comment by ryyppy** [comment]
> The use case was to pass aria-* props to React components from a ui library written in javascript. In our case a company's ui library.

This sounds like you are defining a `type Props = { "aria-label": string }` in your existing React component? This doesn't sound right to me for some reason.

**Comment by ryyppy** [comment]
I will close this for now, feel free to initiate the discussion again if you still feel strongly about it.

**Pull request closed without merging**
