### PR TITLE
Document array spreads

### PR DESCRIPTION
**Pull request by zth**
Available in v11.1.

### CODE REVIEW

**Comment by zth** [comment]
Right, can't merge this until it's actually released (tests fail because of the syntax change, that needs a release to work). Let's wait a bit with this then.

**Comment by fhammerschmidt** [comment]
The syntax lookup probably needs to have a `...`-chapter as well. But not sure if that can even be called spread operator there, since `...` also describes a partially applied function.

**Comment by zth** [comment]
Yeah, maybe it'd be more confusing to document it as a single concept like that. We can think about it for a bit.

**Review by fhammerschmidt — APPROVED** [review]

**Comment by fhammerschmidt** [comment]
This can be merged as well?

**Comment by fhammerschmidt** [comment]
Yes, update "rescript-1110" in `compilers/package.json`

**Pull request merged**
